export const awards = [
  {
    name: '01',
    type: 'Nominee',
    project: 'Animation ( 01 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '02',
    type: 'Nominee',
    project: 'Animation ( 02 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '03',
    type: 'Nominee',
    project: 'Animation ( 03 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '04',
    type: 'Nominee',
    project: 'Animation ( 04 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '05',
    type: 'Nominee',
    project: 'Animation ( 05 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '06',
    type: 'Nominee',
    project: 'Animation ( 06 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '07',
    type: 'Nominee',
    project: 'Animation ( 07 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '08',
    type: 'Nominee',
    project: 'Animation ( 08 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '09',
    type: 'Nominee',
    project: 'Animation ( 09 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '10',
    type: 'Nominee',
    project: 'Animation ( 10 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '11',
    type: 'Nominee',
    project: 'Animation ( 11 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '12',
    type: 'Nominee',
    project: 'Animation ( 12 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '13',
    type: 'Nominee',
    project: 'Animation ( 13 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '14',
    type: 'Nominee',
    project: 'Animation ( 14 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '15',
    type: 'Nominee',
    project: 'Animation ( 15 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '16',
    type: 'Nominee',
    project: 'Animation ( 16 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '17',
    type: 'Nominee',
    project: 'Animation ( 17 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '18',
    type: 'Nominee',
    project: 'Animation ( 18 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '19',
    type: 'Nominee',
    project: 'Animation ( 19 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
  {
    name: '20',
    type: 'Nominee',
    project: 'Animation ( 20 )',
    label: 'Open',
    year: 'Nominating for the Months',
    link: './about.html',
  },
];